### ISSUE TITLE
phase1-coordinator panic when number of chunks is 1

### ISSUE THREAD

**Issue by kellpossible** [AleoHQ/aleo-setup#175]
```
thread 'tests::coordinator_proptest' panicked at 'assertion failed: size != 0', /home/luke/.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.9.0/src/lib.rs:544:9
stack backtrace:
   0: std::panicking::begin_panic
             at /home/luke/.rustup/toolchains/1.48-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:505
   1: itertools::Itertools::chunks
             at /home/luke/.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.9.0/src/lib.rs:544
   2: phase1::helpers::buffers::iter_chunk
             at /home/luke/programming/aleo/aleo-setup/phase1/src/helpers/buffers.rs:48
   3: phase1::computation::<impl phase1::Phase1<E>>::computation
             at /home/luke/programming/aleo/aleo-setup/phase1/src/computation.rs:49
   4: phase1_coordinator::commands::computation::Computation::contribute
             at ./src/commands/computation.rs:151
   5: phase1_coordinator::commands::computation::Computation::run
             at ./src/commands/computation.rs:60
   6: phase1_coordinator::coordinator::Coordinator::run_computation
             at ./src/coordinator.rs:2393
   7: phase1_coordinator::coordinator::Coordinator::contribute
             at ./src/coordinator.rs:2302
```

**Comment by kellpossible** [comment]
Discussing a resolution here https://github.com/AleoHQ/aleo-setup/issues#issuecomment-762165214
